// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetHealthzDefault OK

swagger:response getHealthzDefault
*/
type GetHealthzDefault struct {
	_statusCode int
}

// NewGetHealthzDefault creates GetHealthzDefault with default headers values
func NewGetHealthzDefault(code int) *GetHealthzDefault {
	if code <= 0 {
		code = 500
	}

	return &GetHealthzDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get healthz default response
func (o *GetHealthzDefault) WithStatusCode(code int) *GetHealthzDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get healthz default response
func (o *GetHealthzDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetHealthzDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
