// Code generated by go-swagger; DO NOT EDIT.

// Package restapi go-openapi
//
//  This is the go-openapi swagger example
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v2
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - application/xml
//
// swagger:meta
package restapi
