// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is the go-openapi swagger example",
    "title": "go-openapi",
    "version": "1.0.0"
  },
  "basePath": "/v2",
  "paths": {
    "/login": {
      "post": {
        "description": "Returns token for authorized User",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "operationId": "Login",
        "parameters": [
          {
            "description": "Login Payload",
            "name": "login",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful login",
            "schema": {
              "$ref": "#/definitions/LoginSuccess"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "User not found",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/user/cart": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Get All cart items",
        "tags": [
          "user"
        ],
        "operationId": "GetCart",
        "responses": {
          "200": {
            "description": "All items in cart",
            "schema": {
              "$ref": "#/definitions/CartPreview"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Item Not Found"
          },
          "500": {
            "description": "Server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CartItem": {
      "type": "object",
      "properties": {
        "currency": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "productId": {
          "type": "integer"
        },
        "productName": {
          "type": "string"
        },
        "quantity": {
          "type": "integer"
        },
        "unitPrice": {
          "type": "number"
        }
      }
    },
    "CartPreview": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/CartItem"
      }
    },
    "LoginInfo": {
      "type": "object",
      "required": [
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "LoginSuccess": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "token": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Operations about user",
      "name": "user",
      "externalDocs": {
        "description": "Find out more about our store",
        "url": "http://swagger.io"
      }
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is the go-openapi swagger example",
    "title": "go-openapi",
    "version": "1.0.0"
  },
  "basePath": "/v2",
  "paths": {
    "/login": {
      "post": {
        "description": "Returns token for authorized User",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "operationId": "Login",
        "parameters": [
          {
            "description": "Login Payload",
            "name": "login",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful login",
            "schema": {
              "$ref": "#/definitions/LoginSuccess"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "User not found",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/user/cart": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Get All cart items",
        "tags": [
          "user"
        ],
        "operationId": "GetCart",
        "responses": {
          "200": {
            "description": "All items in cart",
            "schema": {
              "$ref": "#/definitions/CartPreview"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Item Not Found"
          },
          "500": {
            "description": "Server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CartItem": {
      "type": "object",
      "properties": {
        "currency": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "productId": {
          "type": "integer"
        },
        "productName": {
          "type": "string"
        },
        "quantity": {
          "type": "integer"
        },
        "unitPrice": {
          "type": "number"
        }
      }
    },
    "CartPreview": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/CartItem"
      }
    },
    "LoginInfo": {
      "type": "object",
      "required": [
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "LoginSuccess": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "token": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Operations about user",
      "name": "user",
      "externalDocs": {
        "description": "Find out more about our store",
        "url": "http://swagger.io"
      }
    }
  ]
}`))
}
